PROGRAM PUMP_SELECTION
IMPLICIT NONE
REAL::HS,H,F,L,D,V,G,PI,Q,K,RE,N,FO,HEAD_LOSS,POWER,E
INTEGER::STD,I
INTEGER,DIMENSION(10)::STANDARD_PUMP
CHARACTER*10::QUES,FILE,ARRAY

WRITE(*,1)
1 FORMAT(/2X,"ENTER THE LENGHT OF PIPE IN METERS."/)
READ(*,*)L
WRITE(*,2)
2 FORMAT(/2X,"ENTER THE DIAMETER OF THE PIPE IN MILLIMETERS."/)
READ(*,*)D
WRITE(*,3)
3 FORMAT(/2X,"ENTER THE DISCHARGE IN CUBIC METERS PER SECOND."/)
READ(*,*)Q
WRITE(*,4)
4 FORMAT(/2X,"ENTER THE EQUIVALENT ROUGHNESS OF THE PIPE MATERIAL IN METERS."/)
READ(*,*)K
WRITE(*,5)
5 FORMAT(/2X,"ENTER THE KINEMATIC VISCOUSITY OF THE FLUID."/)
READ(*,*)N

D=D/1000

CALL DARCY_WESBACH(F,L,D,V,G,PI,Q,K,RE,N,FO,HEAD_LOSS)

WRITE(*,6)HEAD_LOSS
6 FORMAT(///80("="),20X,"THE HEAD LOSS IS EQUAL TO=",2X,F8.2,1X,"METERS"/80("=")/)

WRITE(*,7)
7 FORMAT(/2X,"ENTER THE STATIC HEAD AVAILABLE IN METERS."/)
READ(*,*)HS

H=HS+HEAD_LOSS

WRITE(*,8)
8 FORMAT(/2X,"ENTER THE EFFECIENCY EXPECTED BY THE PUMP TO BE USED AS %."/)
READ(*,*)E

E=E/100

POWER=Q*H*9.81/E

WRITE(*,9)POWER
9 FORMAT(///80("="),10X,"THE POWER OF THE PUMP TO BE USED SHOULD BE =",2X,F8.2,1X,"KILO WATTS"/80("=")/)

100 WRITE(*,10)
10 FORMAT(/2X,"WOULD YOU LIKE TO READ STANDARD PUMP DATA FROM ARRAY OR LINKED FILE?"/2X,"( ENTER [FILE] OR [ARRAY] )"/)

! THE ENTERY IS CASE SENSITIVE. USER MUST USE CAPITALIZED TEXT.

READ(*,*)QUES

IF(QUES=="ARRAY")THEN

DO I=50,500,50
  STANDARD_PUMP(I/50)=I
  END DO

  ELSE IF(QUES=="FILE")THEN
    OPEN(UNIT=5,FILE="PUMP.TXT")
    DO I=1,10
      READ(5,*)STANDARD_PUMP(I)
      END DO
      ELSE
        WRITE(*,11)
        11 FORMAT(/2X,"SORRY! PLEASE RE-CHECK YOUR SPELLING."/)
        GO TO 100
        END IF
  
  WRITE(*,12)STANDARD_PUMP
  12 FORMAT(/2X,"THE STANDARD PUMP POWERS ARE:"/80("="),20X,10(I3,1X))

 IF(POWER<STANDARD_PUMP(10))THEN
DO I=1,10
  IF(POWER-STANDARD_PUMP(I)<0)THEN
    STD=STANDARD_PUMP(I)
    WRITE(*,13)STD
13 FORMAT(20X,40("-"),///80("="),10X,"USE A STANDARD PUMP OF POWER =",2X,I5,1X,"KILO WATTS"/80("=")/)
    EXIT
    ELSE
      END IF
      END DO
      ELSE
              STD=NINT(POWER/STANDARD_PUMP(10))+1
              WRITE(*,17)STD
              17 FORMAT(20X,40("-"),///80("="),10X,"USE",1X,I3,1X,"STANDARD PUMPS OF POWER = 500 KILO WATTS"/80("=")/)
    		END IF

END PROGRAM


SUBROUTINE DARCY_WESBACH(F,L,D,V,G,PI,Q,K,RE,N,FO,HF)
IMPLICIT NONE
Real:: HF,F,L,D,V,Q,K,RE,N,FO,G,PI
FO=1
G=9.81
PI=3.14
V=Q/(PI*D**2/4)
RE=V*D/N
IF (RE<2100) THEN
    F=64/RE
    Else
    DO
    F=(-2.0*LOG10(K/3.7/D+2.51/RE/SQRT(FO)))**(-2)
    IF (ABS((F-FO)/F)<=0.0001) EXIT 
    FO=F
    END DO
END IF

HF=F*L/D*(V**2)/(2*G)

END SUBROUTINE