MODULE SUB_DISTRIBUTION_FACTOR
USE global  
IMPLICIT NONE

CONTAINS
SUBROUTINE DISTRIBUTION_FACTOR(DF,N,SPANLENGTH,FREE_END,FIXED_END)
IMPLICIT NONE

!CALLING ARGUMENTS:
INTEGER,INTENT(IN)::N
REAL(double_precision),DIMENSION(N),INTENT(IN)::SPANLENGTH
REAL(double_precision),DIMENSION(N*2),INTENT(OUT)::DF
CHARACTER(LEN=*),INTENT(IN)::FREE_END, FIXED_END

!LOCAL VARIABLES:
REAL(double_precision),DIMENSION(N)::STIFFNESS     !STIFFNESS IS A LOCAL ARRAY BECAUSE WE DON'T GET IT FROM THE MAIN PROGRAM NOR IS IT PASSED BACK TO IT
INTEGER::I                       !IT IS JUST NEEDED IN THIS SUBROUTINE SO I DELETED IT'S DECLARATION FROM THE MAIN PROGRAM.

DO I=1,N
  STIFFNESS(I)=1/SPANLENGTH(I)
END DO
  
  DO I=1,N*2
    IF(I==1.AND.(FREE_END=='L'.OR.FREE_END=='LR')) THEN                        
      DF(I)=0
      ELSE IF (I==N*2.AND.(FREE_END=='R'.OR.FREE_END=='LR')) THEN                
      DF(I)=0 
      ELSE IF (I==2.AND.(FREE_END=='L'.OR.FREE_END=='LR')) THEN                 
      DF(I)=0
      ELSE IF (I==N*2-1.AND.(FREE_END=='R'.OR.FREE_END=='LR')) THEN             
      DF(I)=0
      ELSE IF (I==3.AND.(FREE_END=='L'.OR.FREE_END=='LR')) THEN                 
      DF(I)=1
      ELSE IF (I==N*2-2.AND.(FREE_END=='R'.OR.FREE_END=='LR')) THEN             
      DF(I)=1
      ELSE IF (I==1.AND.(FIXED_END=='L'.OR.FIXED_END=='LR'))THEN                
      DF(I)=0
      ELSE IF (I==N*2.AND.(FIXED_END=='R'.OR.FIXED_END=='LR'))THEN              
      DF(I)=0   
      ELSE IF(I==1)THEN
      DF(I)=1
      ELSE IF (I==(N*2))THEN
      DF(I)=1
	  ELSE IF((MOD(REAL(I),2.0))==0)THEN
      DF(I)=STIFFNESS(I/2)/(STIFFNESS(I/2)+(STIFFNESS((I/2)+1)))
      ELSE
      DF(I)=STIFFNESS((I+1)/2)/(STIFFNESS((I+1)/2)+(STIFFNESS(((I+1)/2)-1)))
    END IF
  END DO

END SUBROUTINE

END MODULE